---
- name: Installing packages
  yum:
    name: "{{ item }}"
    state: present
  notify:
  - restart {{ item }}
  loop: "{{ package }}"
  when: ansible_distribution == "Rocky"

- name: Copying files to web root
  copy:
    src: index.html
    dest: /var/www/html/index.html
  when: ansible_distribution == "Rocky"

- name: Configuring firewall
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled
  when: ansible_distribution == "Rocky"
