---
- name: Installing
  include_tasks: install.yml
  when: ansible_distribution == "Rocky" and input  == "install"

- name: Uninstalling 
  include_tasks: uninstall.yml
  when: ansible_distribution == "Rocky" and input  == "uninstall"
